server:
  port: 3031
installmentpoc:
  faultchance: ${FAUT_CHANCE:-0}
  fatalfaultchance: ${FATAL_FAULT_CHANCE:-0}
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: installment-poc
  sql.init:
    platform: postgres
    schema-locations: classpath:/schema.sql
    mode: always
  datasource:
    username: ${POSTGRES_USER:-postgres}
    password: ${POSTGRES_PASSWORD:-postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:-localhost}:5432/${POSTGRES_DB:-charge}
    hikari.connectionTimeout: 20000
    hikari.maximumPoolSize: 5
  temporal:
    namespace: ${TEMPORAL_NAMESPACE:default}
    connection:
      target: ${TEMPORAL_CONNECTION_TARGET:localhost:7233}
    workersAutoDiscovery:
      packages: org.malchun.installmentpoc
springdoc:
  api-docs:
    version: openapi_3_1
    path: /api-docs
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    export:
      prometheus:
        enabled: true
logging.level.com.malchun.installmentpoc: DEBUG
logging.level.ROOT: INFO