services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: installment-app
    ports:
      - 3031:3031
    networks:
      - proxyapp-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TEMPORAL_CONNECTION_TARGET=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
      - FAULT_CHANCE=0.5
      - FATAL_FAULT_CHANCE=0.2

networks:
  proxyapp-network:
    external:
      name: installment-network